### ISSUE TITLE
Config is overwritten to defaults when the game starts

### ISSUE THREAD

**Issue by roberestarkk** [StrikerRockers-Mods/ClearDespawn-Fabric#10]
My server has the despawn time set at 1500 ticks.
I have tried changing this value while on the server, from the main title menu, and even in the .toml file.
In each case, as soon as I quit out and load up the game again, the value is reset to 6000.

On v1.1.7

**Comment by strikerrocker** [comment]
What modloader forge or fabric?

**Comment by roberestarkk** [comment]
On Fabric.
Also tested on v1.1.8 and same problem.
