### ISSUE TITLE
It doesn't work period

### ISSUE THREAD

**Issue by LordEnder-Kitty** [StrikerRockers-Mods/ClearDespawn-Fabric#15]
it just doesn't work at all. is it incompatible with anything because i have a few mods that rewrite the rendering engines so maybe thats causing an issue?

**Comment by strikerrocker** [comment]
First of all what modloader, minecraft version, mod version. 
Also if anything that replaces rendering engines it may probably the issue. I would recommend testing without those mods.

**Comment by LordEnder-Kitty** [comment]
sorry, i don't check github that often. i use quite a few mods that change the rendering engine cause i have a bad computer. so yeah, that might be the issue.

**Comment by cjtganzon** [comment]
I tested with my modpack and it seems to not work, but it does work alone, so it might be another mod causing it

**Comment by strikerrocker** [comment]
Closing due to no information
