### ISSUE TITLE
1.19.4 pls

### ISSUE THREAD

**Issue by Nukecraft5419** [StrikerRockers-Mods/ClearDespawn-Fabric#18]

**Comment by strikerrocker** [comment]
Try the 1.19.3 version it should work fine.

**Comment by Nukecraft5419** [comment]
The problem is that the tag and 1.19.3 can run for 1.19.4 but with packwiz I cannot insert it via commands because it appears for 1.19.3

**Comment by strikerrocker** [comment]
I have updated the tag already.

**Comment by Nukecraft5419** [comment]
Many thanks from the LifeMC Studios team
