### ISSUE TITLE
1.20.1-1.1.11 not working with 1.20

### ISSUE THREAD

**Issue by PokeMaserJ** [StrikerRockers-Mods/ClearDespawn-Fabric#20]
"Mod ID: 'forge', Requested by: 'cleardespawn', Expected range: '[47,)', Actual version: '46.0.14'" in my logs. Forge 47 stared with 1.20.1

**Comment by strikerrocker** [comment]
New version 1.1.12 which now support both Minecraft 1.20 and 1.20.1 has been released.
