### ISSUE TITLE
1.1.15, 1.20.1: NeoForge considered a missing mod despite being installed

### ISSUE THREAD

**Issue by MrFastZombie** [StrikerRockers-Mods/ClearDespawn-Fabric#26]
NeoForge Version: 47.1.84
ClearDespawn: 1.1.15

With this versions on 1.20.1, the launcher will show this error:
`Mod ID: 'neoforge', Requested by: 'cleardespawn', Expected range: '[1,)', Actual version: '[MISSING]'`

**Comment by strikerrocker** [comment]
Invalidly marked the file as supporting 1.20.1 it should only work on 1.20.2. Fixed the verison.
