### ISSUE TITLE
Massive lag with Iris

### ISSUE THREAD

**Issue by srnyx** [StrikerRockers-Mods/ClearDespawn-Fabric#5]
When using v1.1.2, the game lags when enabling shaders when using Iris. Switching back to v1.1.1 fixes it.

**Comment by srnyx** [comment]
Okay now it's not happening, I didn't change a thing. So weird.

**Comment by strikerrocker** [comment]
Its something unrelated to this mod? Maybe you didn't wait for the world to load?
