### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by Disguys** [StrikerRockers-Mods/ClearDespawn-Fabric#7]
don't know why, but for some reason there was a crash due to ClearDespawn.
Fabric Loader - 0.12.12
MC Version - 1.18.1
Crash log - https://crashy.net/JsGL5RAcK2Bwr3utGta6

**Comment by strikerrocker** [comment]
Can you try deleting the config file for this mod and trying again? I think the config file is written wrong.

**Comment by strikerrocker** [comment]
Hey any updates?

**Comment by Disguys** [comment]
I apologize for the long answer, I completely forgot.
Everything is fine already, there was a crash twice, then I updated Fabric and everything worked.
